Migrate to Heartwood
Signed-off-by: xphoniex <dj.2dixx@gmail.com>

diff --git a/scripts/create-seed-fixture b/scripts/create-seed-fixture
--- a/scripts/create-seed-fixture
+++ b/scripts/create-seed-fixture
@@ -1,14 +1,13 @@
 #!/usr/bin/env bash
 set -euo pipefail
 
-function cleanup {
-  docker kill radicle-git-server-test
-}
-trap cleanup EXIT
-
+#function cleanup {
+#  docker kill radicle-git-server-test
+#}
+#trap cleanup EXIT
 
 PASSPHRASE=asdf
-REV=40bdc662b2d48cbfaa87182b21457ef8f861b04a
+SEED="0.0.0.0:8080"
 
 REPO_ROOT=$(git rev-parse --show-toplevel)
 ID=$(echo $RANDOM | md5sum | head -c 8)
@@ -33,29 +32,19 @@ mkdir -p $TEST_REPO_PATH
 
 tar -xf $TEST_REPO_ARCHIVE -C $TEST_REPO_PATH
 
-RAD_HOME=$PALM_RAD_HOME rad auth --init --name palm --passphrase $PASSPHRASE
+RAD_HOME=$PALM_RAD_HOME RAD_PASSPHRASE=$PASSPHRASE rad auth
 
-docker run \
-  --detach \
-  --init \
-  --publish 8778:8778 \
-  --rm \
-  --env RAD_HOME=/app/radicle \
-  --name radicle-git-server-test \
-  --volume $PALM_RAD_HOME:/app/radicle \
-  "gcr.io/radicle-services/git-server:$REV" \
-  --passphrase $PASSPHRASE \
-  --allow-unauthorized-keys
+#RAD_HOME=$PALM_RAD_HOME radicle-httpd &
 
 # git-server takes a while to copy commit hooks to the monorepo
-sleep 10
+sleep 1
 
 GIT_AUTHOR_NAME="Alice Liddell"
 GIT_AUTHOR_EMAIL="alice@radicle.xyz"
 GIT_COMMITTER_NAME="Alice Liddell"
 GIT_COMMITTER_EMAIL="alice@radicle.xyz"
 
-RAD_HOME=$ALICE_RAD_HOME rad auth --init --name alice --passphrase $PASSPHRASE
+RAD_DEBUG=1 RAD_HOME=$ALICE_RAD_HOME RAD_PASSPHRASE=$PASSPHRASE rad auth
 
 cd $ALICE_CHECKOUT
 
@@ -65,30 +54,29 @@ git checkout feature/branch
 git checkout orphaned-branch
 git checkout main
 
-RAD_HOME=$ALICE_RAD_HOME rad init --name "source-browsing" --description "Git repository for source browsing tests" --default-branch "main" --no-confirm
-
-sleep 10
-RAD_HOME=$ALICE_RAD_HOME rad push --seed 0.0.0.0:8778 --all --sync
-PROJECT_ID=$(rad .)
+RAD_HOME=$ALICE_RAD_HOME RAD_PASSPHRASE=$PASSPHRASE rad init --name "source-browsing" --description "Git repository for source browsing tests" --default-branch "main" --no-confirm
+#RAD_HOME=$ALICE_RAD_HOME RAD_PASSPHRASE=$PASSPHRASE rad push --seed $SEED --all --sync
+PROJECT_ID=$(RAD_HOME=$ALICE_RAD_HOME RAD_PASSPHRASE=$PASSPHRASE rad .)
 
 
-GIT_AUTHOR_NAME="Bob Belcher"
-GIT_AUTHOR_EMAIL="bob@radicle.xyz"
-GIT_COMMITTER_NAME="Bob Belcher"
-GIT_COMMITTER_EMAIL="bob@radicle.xyz"
+#GIT_AUTHOR_NAME="Bob Belcher"
+#GIT_AUTHOR_EMAIL="bob@radicle.xyz"
+#GIT_COMMITTER_NAME="Bob Belcher"
+#GIT_COMMITTER_EMAIL="bob@radicle.xyz"
 
-RAD_HOME=$BOB_RAD_HOME rad auth --init --name bob --passphrase $PASSPHRASE
+#RAD_HOME=$BOB_RAD_HOME RAD_PASSPHRASE=$PASSPHRASE rad auth
 
-cd $BOB_CHECKOUT
-RAD_HOME=$BOB_RAD_HOME rad clone $PROJECT_ID --seed 0.0.0.0:8778 --no-confirm
+#cd $BOB_CHECKOUT
+#RAD_HOME=$BOB_RAD_HOME rad clone $PROJECT_ID --seed $SEED --no-confirm
 
-cd $TEST_REPO_NAME
-echo "Updated readme" > README.md
-git add README.md
-git commit --message "Update readme" --date "Mon Nov 21 14:00 2022 +0100"
-RAD_HOME=$BOB_RAD_HOME rad push --seed 0.0.0.0:8778
-RAD_HOME=$BOB_RAD_HOME rad sync --seed 0.0.0.0:8778 --self
-RAD_HOME=$BOB_RAD_HOME rad sync --seed 0.0.0.0:8778
+#cd $TEST_REPO_NAME
+#echo "Updated readme" > README.md
+#git add README.md
+#git commit --message "Update readme" --date "Mon Nov 21 14:00 2022 +0100"
+#RAD_HOME=$BOB_RAD_HOME rad push --seed $SEED
+#RAD_HOME=$BOB_RAD_HOME rad sync --seed $SEED --self
+#RAD_HOME=$BOB_RAD_HOME rad sync --seed $SEED
 
 cd $BASE_PATH
-tar -cjf palm.tar.bz2 --exclude "post-receive" --exclude "pre-receive" -C $PALM_RAD_HOME .
+#tar -cjf palm.tar.bz2 --exclude "post-receive" --exclude "pre-receive" -C $PALM_RAD_HOME .
+tar -cjf palm.tar.bz2 --exclude "post-receive" --exclude "pre-receive" -C $ALICE_RAD_HOME .
